### ISSUE TITLE
Any suggestions for embedded system programmers? 

### ISSUE THREAD

**Issue by nurimbet** [mtdvio/every-programmer-should-know#142]

**Comment by Tunlier** [comment]
I think we have a few here but not directly related to embedded. Glad someone mentioned it.

**Comment by KathrynN** [comment]
A friend suggested this book as a great foundational text:
https://csapp.cs.cmu.edu/

**Comment by siriniok** [comment]
This guide is not intended to provide resources on any specific technologies or stacks, we focus on widely applicable knowledge/skills instead.

Take a look at [Awesome-Embedded](https://github.com/nhivp/Awesome-Embedded) or [awesome-embedded](https://github.com/embedded-boston/awesome-embedded-systems).
