### ISSUE TITLE
Any suggestions for Golang resources ? 

### ISSUE THREAD

**Issue by zatamine** [mtdvio/every-programmer-should-know#151]

**Comment by davidlanouette** [comment]
The guide doesn't currently have any language specific resources.  It's intended to be a place for "general purpose" information.  My personal opinion is that it should remain that way (I am not a maintainer.)

That being said, if there were other language specific lists of resources, we could link to those.

Specifically for go, take a look at the [Awesome Go](https://awesome-go.com/) site.  Specifically the Tutorials section at the bottom.  That might be something useful to you.

**Comment by siriniok** [comment]
Closing for the reasons described by @davidlanouette
