### ISSUE TITLE
Grammar contributing.md

### ISSUE THREAD

**Issue by CHBaker** [mtdvio/every-programmer-should-know#93]
the line in contributing.md:

> This is why we strive to having less, but most valuable resources in the list.

should grammatically be:

> This is why we strive to having less, but more valuable resources in the list.

or better yet

> We strive to have a smaller list of more valuable resources, quality over quantity.

**Comment by mr-mig** [comment]
Make a PR

**Comment by CHBaker** [comment]
can do
